name: restaurant_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.5.3+2
  firebase_core: ^1.18.0
  cloud_firestore: 3.1.18
  uuid: ^3.0.6
  intl: ^0.17.0
  cached_network_image: ^3.2.1
  flutter_launcher_icons: 0.9.3
  flutter_native_splash: 2.2.3+1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path: assets/images/logo_app.png
  android: true
  ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo_app.png
  color_dark: "#121212"
  image_dark: assets/images/logo_app.png

  android_12:
    image: assets/images/logo_app.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo_app.png
    icon_background_color_dark: "#121212"

  web: false

flutter: 
  assets: 
    - assets/images/
    - assets/fonts/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
  uses-material-design: true

